version: '1.0.0.{build}'
image: Visual Studio 2017
branches:
    only:
        - master

before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: dotnet build -c Release

test_script:
    -cmd: cd POCOMapper.Test
    -cmd: dotnet test -c Release

deploy: off
