version: '1.0.0.{build}'
image: Visual Studio 2017

branches:
    only:
        - master

shallow_clone: true
clone_folder: C:\projects\pocomapper

before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: dotnet build -c Release POCOMapper
    - cmd: dotnet build -c Release POCOMapper.Test

test_script:
    - cmd: dotnet test -c Release -f net40 --logger "trx;LogFileName=C:\projects\pocomapper\testresult-net40.xml" POCOMapper.Test
    - cmd: dotnet test -c Release -f netcoreapp2.0 --logger "trx;LogFileName=C:\projects\pocomapper\testresult-netcore.xml" POCOMapper.Test

on_finish:
    - ps: |
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path C:\projects\pocomapper\testresult-net40*.xml))
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path C:\projects\pocomapper\testresult-netcore*.xml))

deploy: off
