version: '1.0.0.{build}'
image: Visual Studio 2017
branches:
    only:
        - master

before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: >-
        dotnet build -c Release POCOMapper
        dotnet build -c Release POCOMapper.Test

test_script:
    - ps: >-
        dotnet test -c Release --logger "trx;LogFileName=testresult.xml" POCOMapper.Test
        $testExit = $lastExitCode
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", "C:\projects\pocomapper\tests\POCOMapper.Test\TestResults\testresult.xml")

deploy: off
